### ISSUE TITLE
To be, or not to be

### ISSUE THREAD

**Issue by chengjun4260** [chengjun4260/d8d-panghu#1]
1.下发是否涉及对接，是否需要通知对方服务器？
2.对接的具体（是否仅创建，回调和查询状态）
3.同步回调是页面轮询状态，成功就返回指定页面吗？
4.异步回调是携带参数访问指定url吗？

**Comment by chengjun777** [comment]
test response

**Comment by chengjun4260** [comment]
师傅，因为没实现过对接，麻烦解释详细通俗点，我看完就删，争取没有二次交流
